module(load="imfile" PollingInterval="10")

input(type="imfile" File="/var/log/mysql/mysql.log" Tag="mysql-general:" Severity="info" Facility="local6")
input(type="imfile" File="/var/log/mysql/error.log" Tag="mysql-error:" Severity="error" Facility="local6")
input(type="imfile" File="/var/log/mysql/mysql-slow.log" Tag="mysql-slow:" Severity="info" Facility="local6")
input(type="imfile" File="/var/log/mysql/audit.log" Tag="mysql-audit:" Severity="info" Facility="local6")

# TCP forwarding. Replace IP and port.
local6.* @@SIEM_COLLECTOR_IP:514
